my:
    servers:
        - dev.bar.com
        - foo.bar.com
        
    candidateServers:
        - dev2.bar.com
        - foo2.bar.com
    
---

spring:
    profiles: development

my:
    servers:
        - dev.bar.com
        - foo.bar.com
    
    candidateServers:
        - dev2.bar.com
        - foo2.bar.com
    
---
    
spring:
    profiles: production

my:
    servers:
        - live.bar.com
        - foo.bar.com
        
    candidateServers:
        - live2.bar.com
        - foo2.bar.com